### PR TITLE
Update Project Lifecycle to add security expectation to Impact Stage acceptance criteria

### PR DESCRIPTION
**Pull request by brian-jarvis-aws**
Discussed in #41. This change adds some expectations for how a proposed Impact Stage project should document their security policy management and processes.

The second diff on L189 appears to just be an unintentional whitespace or newline change introduced by GH in the editing process and can be safely ignored.

### CODE REVIEW

**Review by maximilien — COMMENTED** [review]
LGTM

**Comment by brian-jarvis-aws** [comment]
Can I get one more review, please @PQCA/tac

**Comment by brian-jarvis-aws** [comment]
> LGTM

Would you mind converting this to an approve action on the review please, @maximilien

**Comment by brian-jarvis-aws** [comment]
Requesting another review on this one please
@planetf1 @ashman-p @sam-stanwyck @zadlg

**Review by ashman-p — APPROVED** [review]

**Pull request merged**
